name: Build and Deploy on gh-page
on:
  push:
    branches:
      - master
jobs:
  app-build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Tests
        run: yarn test -u
      - name: Build
        run: yarn build
        env:
          PUBLIC_URL: https://mikbry.github.io
          CONTENT_BASE: /jtyper
          NODE_ENV: production

      - name: Deploy app
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: build # The folder the action should deploy.
          TARGET_FOLDER: /
